services:
  worker:
    image: ${WORKER_IMAGE:-cjarn/docker-panel-lite-worker:latest}
    build:
      context: .
      dockerfile: services/worker/Dockerfile
  worker-go:
    image: ${WORKER_GO_IMAGE:-cjarn/docker-panel-lite-worker:go}
    build:
      context: .
      dockerfile: services/worker-go/Dockerfile
