export type Repository = {
  id: string;
  alias: string;
  url: string;
  branch: string;
  mode: "compose" | "dockerfile";
  composeFile: string;
  dockerfile: string;
  credentialId: string;
  environment: Record<string, string>;
  domain: string;
  service: string;
  internalPort: number;
  ports?: string;
  publicTunnelEnabled?: boolean;
  publicTunnelDomain?: string;
  publicTunnelDomains?: Record<string, string>;
  publicTunnelPorts?: Record<string, string>;
  publicUrl?: string;
  publicUrls?: Record<string, string>;
  publicTunnels?: Record<string, { url?: string; target?: string; domain?: string; workerId?: string; workerLabel?: string; updatedAt?: number }>;
  publicTunnelStatus?: string;
  publicTunnelTarget?: string;
  publicTunnelWorkerId?: string;
  publicTunnelWorkerLabel?: string;
  publicTunnelUpdatedAt?: number;
  ngrokTokenSecret?: boolean;
  ngrokTokenMask?: string;
  poolId: string;
  availableBranches?: string[];
  composeContent?: string;
  createdAt: number;
  updatedAt: number;
  scope?: "workspace";
  sharing?: "private" | "shared" | "public";
  shared?: boolean;
  public?: boolean;
  sharingUpdatedAt?: number;
  sharingUpdatedBy?: string;
  ownerUid?: string;
  ownerEmail?: string;
  sharedEmails?: string[];
  createdBy?: string;
  updatedBy?: string;
};

export type CredentialSummary = {
  id: string;
  alias: string;
  username: string;
  tokenMask: string;
  updatedAt: number;
  scope?: "workspace";
  sharing?: "private" | "shared" | "public";
  shared?: boolean;
  public?: boolean;
  sharingUpdatedAt?: number;
  sharingUpdatedBy?: string;
  ownerUid?: string;
  ownerEmail?: string;
  sharedEmails?: string[];
  createdAt?: number;
  createdBy?: string;
  updatedBy?: string;
};

export type CommandPreset = {
  id: string;
  name: string;
  description?: string;
  command: string;
  createdAt: number;
  updatedAt: number;
};

export type Deployment = {
  id: string;
  repositoryId: string;
  containerId?: string;
  containerRef?: string;
  action: string;
  status: string;
  progress: number;
  workerId?: string;
  targetWorkerId?: string;
  message?: string;
  command?: string;
  commandOutput?: string;
  commandExitCode?: number;
  tunnelService?: string;
  tunnelReset?: boolean;
  timeoutSeconds?: number;
  createdAt: number;
  startedAt?: number;
  finishedAt?: number;
  leaseExpiresAt?: number;
};

export type AppLog = {
  id: string;
  actorType: "worker" | "ui";
  actorId: string;
  actorEmail?: string;
  actorLabel?: string;
  runtime?: "worker-python" | "worker-go" | "web";
  functionName?: string;
  action: string;
  source: string;
  severity: "error";
  message: string;
  context?: Record<string, string>;
  createdAt: number;
};

export type Agent = {
  id: string;
  identitySource?: string;
  status: "online" | "offline" | "draining" | "stopping";
  label?: string;
  hostname: string;
  location?: string;
  poolId?: string;
  sharing?: "private" | "shared" | "public";
  shared?: boolean;
  public?: boolean;
  sharingUpdatedAt?: number;
  sharingUpdatedBy?: string;
  workerTokenHash?: string;
  claimedAt?: number;
  claimedBy?: string;
  ownerUid?: string;
  ownerEmail?: string;
  sharedEmails?: string[];
  activeJobs: number;
  maxConcurrency: number;
  shards?: string[];
  lastHeartbeat: number;
  startedAt?: number;
  stoppingAt?: number;
  pid?: number;
  runtime?: string;
  runtimeVersion?: string;
  workerVersion?: string;
  features?: string[];
  goVersion?: string;
  pythonVersion?: string;
  platform?: string;
  system?: string;
  machine?: string;
  executable?: string;
  cloneDir?: string;
  dataDir?: string;
  ngrokEnabled?: boolean;
  ngrokRegion?: string;
  leaseSeconds?: number;
  pollSeconds?: number;
  docker?: {
    available?: boolean;
    serverVersion?: string;
    apiVersion?: string;
    os?: string;
    architecture?: string;
    containers?: number;
    containersRunning?: number;
    images?: number;
    error?: string;
  };
};

export type ManagedContainer = {
  id: string;
  dockerId?: string;
  name: string;
  image: string;
  status: string;
  project: string;
  composeService?: string;
  publicUrl?: string;
  publicUrls?: Record<string, string>;
  publicTunnelStatus?: string;
  publicTunnelTarget?: string;
  publicTunnelUpdatedAt?: number;
  ports: string[];
  workerId?: string;
  workerLabel?: string;
  workerHostname?: string;
  isWorkerContainer?: boolean;
  protectedActions?: string[];
  poolId?: string;
  logTail?: string;
  createdAt?: number;
  lastSeenAt?: number;
  missingSince?: number;
  updatedAt: number;
};
